---

# install Nginx
- debug: msg="pkg manager - {{ ansible_pkg_mgr }}"

- name: install nginx
  action: "{{ ansible_pkg_mgr }} name=nginx state=present"

# config files
- include: config.yml

# start Nginx
- name: start nginx service
  service: name=nginx state=started
