---

# install Nginx
- debug: msg="pkg manager - {{ ansible_pkg_mgr }}"

- name: install nginx
  sudo: true
  action: "{{ ansible_pkg_mgr }} name=nginx state=present"

# config files
- include: config.yml

# start Nginx
- name: start nginx service
  debug: msg="nginx_run_service - {{ nginx_run_service | default(false) }}"
  sudo: true
  when: nginx_run_service | default(false)
  notify:
    - start nginx
