---
- name: start nginx
  sudo: true
  service: name=nginx state=started
  when: nginx_run_service | default(false)

- name: restart nginx
  sudo: true
  service: name=nginx state=restarted
  when: nginx_run_service | default(false)

- name: reload nginx
  sudo: true
  service: name=nginx state=reloaded
  when: nginx_run_service | default(false)
